name: skip-long-tests
description: add -short flag to GOFLAGS to skip long running tests

runs:
  using: "composite"
  steps:
    - name: Skip long running tests
      shell: bash
      run: echo "GOFLAGS=$GOFLAGS -short" >> $GITHUB_ENV
