// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package internal

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufSerializedState = []byte{131}

func (t *SerializedState) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufSerializedState); err != nil {
		return err
	}

	// t.QuadsEnqueued (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.QuadsEnqueued)); err != nil {
		return err
	}

	// t.Buffer ([]uint8) (slice)
	if len(t.Buffer) > 2097152 {
		return xerrors.Errorf("Byte array in field t.Buffer was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(t.Buffer))); err != nil {
		return err
	}

	if _, err := cw.Write(t.Buffer); err != nil {
		return err
	}

	// t.LayerQueueTwinholds ([][]uint8) (slice)
	if len(t.LayerQueueTwinholds) > 8192 {
		return xerrors.Errorf("Slice value in field t.LayerQueueTwinholds was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.LayerQueueTwinholds))); err != nil {
		return err
	}
	for _, v := range t.LayerQueueTwinholds {
		if len(v) > 2097152 {
			return xerrors.Errorf("Byte array in field v was too long")
		}

		if err := cw.WriteMajorTypeHeader(cbg.MajByteString, uint64(len(v))); err != nil {
			return err
		}

		if _, err := cw.Write(v); err != nil {
			return err
		}

	}
	return nil
}

func (t *SerializedState) UnmarshalCBOR(r io.Reader) (err error) {
	*t = SerializedState{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.QuadsEnqueued (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.QuadsEnqueued = uint64(extra)

	}
	// t.Buffer ([]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 2097152 {
		return fmt.Errorf("t.Buffer: byte array too large (%d)", extra)
	}
	if maj != cbg.MajByteString {
		return fmt.Errorf("expected byte array")
	}

	if extra > 0 {
		t.Buffer = make([]uint8, extra)
	}

	if _, err := io.ReadFull(cr, t.Buffer); err != nil {
		return err
	}

	// t.LayerQueueTwinholds ([][]uint8) (slice)

	maj, extra, err = cr.ReadHeader()
	if err != nil {
		return err
	}

	if extra > 8192 {
		return fmt.Errorf("t.LayerQueueTwinholds: array too large (%d)", extra)
	}

	if maj != cbg.MajArray {
		return fmt.Errorf("expected cbor array")
	}

	if extra > 0 {
		t.LayerQueueTwinholds = make([][]uint8, extra)
	}

	for i := 0; i < int(extra); i++ {
		{
			var maj byte
			var extra uint64
			var err error
			_ = maj
			_ = extra
			_ = err

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 2097152 {
				return fmt.Errorf("t.LayerQueueTwinholds[i]: byte array too large (%d)", extra)
			}
			if maj != cbg.MajByteString {
				return fmt.Errorf("expected byte array")
			}

			if extra > 0 {
				t.LayerQueueTwinholds[i] = make([]uint8, extra)
			}

			if _, err := io.ReadFull(cr, t.LayerQueueTwinholds[i]); err != nil {
				return err
			}

		}
	}
	return nil
}
